# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  PROJECT_PATH: 'HermesCarrierLibrary/HermesCarrierLibrary.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'
  
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install MAUI
      run: dotnet workload install maui --ignore-failed-sources
    - name: Restore packages
      run: dotnet restore ${{ env.PROJECT_PATH }}      
    - name: Build project
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore
    - name: Get Next Version Action
      uses: technote-space/get-next-version-action@v1.1.1
    - name: Pack project
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --include-symbols -p:PackageVersion=${process.env.NEXT_VERSION} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
    - name: Push package
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg --source ${{ env.NUGET_SOURCE_URL }} --api-key ${{ secrets.NUGET_API_KEY }}
      
